# Generated by Django 3.0.1 on 2020-01-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('book_title', models.CharField(max_length=150)),
                ('campus', models.CharField(choices=[('LC', 'Lincoln Center'), ('RH', 'Rose Hill')], max_length=2)),
                ('professor', models.CharField(max_length=20)),
                ('class_subject', models.CharField(max_length=8)),
                ('class_section', models.CharField(blank=True, max_length=3, null=True)),
                ('semester', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring'), ('U', 'Summer')], max_length=1)),
                ('year', models.SmallIntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')])),
                ('online_code', models.BooleanField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('condition', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Mind'), (3, 'Used'), (4, 'Bad'), (5, 'Unusable/Missing Parts')])),
                ('reprint', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
