# Generated by Django 3.0.1 on 2020-01-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reprint',
        ),
        migrations.AddField(
            model_name='book',
            name='post_type',
            field=models.BooleanField(default=True, verbose_name='Offer(T)/Ask(F)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='campus',
            field=models.CharField(choices=[('LC', 'Lincoln Center'), ('RH', 'Rose Hill'), ('LR', 'Both')], max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Mint'), (3, 'Used'), (4, 'Bad'), (5, 'Unusable/Missing Parts')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
