# Generated by Django 3.0.1 on 2020-01-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200119_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contact_info',
            field=models.TextField(default='Contact info not provided.', max_length=200),
        ),
    ]
